name: employee_leave
channels:
  - defaults
dependencies:
  - ca-certificates=2021.9.30
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tzdata=2021a
  - wheel=0.37.0
  - pip:
    - anyio==3.3.4
    - asgiref==3.4.1
    - atomicwrites==1.4.0
    - attrs==21.2.0
    - click==8.0.3
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - fastapi==0.70.0
    - future==0.18.2
    - h11==0.12.0
    - hyperopt==0.2.5
    - idna==3.3
    - iniconfig==1.1.1
    - joblib==1.1.0
    - joblist==2.0.3
    - networkx==2.6.3
    - numpy==1.21.3
    - packaging==21.0
    - pandas==1.3.4
    - plotly==5.3.1
    - pluggy==1.0.0
    - py==1.10.0
    - pydantic==1.8.2
    - pyparsing==2.4.7
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - scikit-learn==0.24.1
    - scipy==1.7.1
    - six==1.16.0
    - sniffio==1.2.0
    - starlette==0.16.0
    - tenacity==8.0.1
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - uvicorn==0.15.0
    - w3lib==1.22.0
    - xgboost==1.5.0
    - wincertstore==0.2
